name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changelog updates
        run: |
          git fetch origin next
          if ! git diff --name-only origin/next...HEAD | grep -q "docs/pages/resources/changelog.md"; then
            echo "no_changelog=true" >> $GITHUB_ENV
          fi

      - name: Comment on PR
        if: env.no_changelog == 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ❌ No changelog entry was found. Please add an entry to `docs/pages/resources/changelog.md`.
