name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changelog updates
        run: |
          if ! git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "docs/pages/resources/changelog.md"; then
            echo "no_changelog=true" >> $GITHUB_ENV
          fi

      - name: Comment on PR
        if: env.no_changelog == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: '❌ No changelog entry was found. Please add an entry to `docs/pages/resources/changelog.md`.'
            })
