name: Check Changelog
on:
 pull_request:
   types: [assigned, opened, synchronize, reopened]
   branches:
     - next
permissions:
 contents: read
 issues: write
 pull-requests: write
jobs:
 check-changelog:
   runs-on: ubuntu-latest
   steps:
     - uses: tarides/changelog-check-action@v2
       with:
         changelog: docs/pages/resources/changelog.md
